/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html"],
  theme: {
    extend: {
      "colors": {
        "surface-slate": "#F8FAFC",
        "error-container": "#ffdad6",
        "inverse-surface": "#213145",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#111c2d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdeab",
        "tertiary-fixed": "#d8e3fb",
        "outline-variant": "#c6c6cd",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#bcc7de",
        "outline": "#76777d",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#79849a",
        "on-secondary-fixed": "#271900",
        "surface-container": "#e5eeff",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#e3c28e",
        "surface-ivory": "#FDFDFB",
        "surface-tint": "#565e74",
        "secondary-container": "#fddba5",
        "surface": "#f8f9ff",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "prestige-gold": "#C5A059",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#3c475a",
        "background": "#f8f9ff",
        "on-surface-variant": "#45464d",
        "primary-container": "#131b2e",
        "tertiary-container": "#111c2d",
        "on-secondary-fixed-variant": "#5a431b",
        "on-secondary-container": "#785f34",
        "inverse-primary": "#bec6e0",
        "primary-fixed-dim": "#bec6e0",
        "primary": "#000000",
        "on-error-container": "#93000a",
        "secondary": "#735a30",
        "on-primary-fixed": "#131b2e",
        "surface-dim": "#cbdbf5"
      },
      "spacing": {
        "margin-mobile": "16px",
        "container-max": "1200px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "section-gap": "80px",
        "unit": "8px"
      },
      "fontFamily": {
        "label-md": ["Noto Sans JP"],
        "headline-md": ["Noto Serif JP"],
        "body-lg": ["Noto Sans JP"],
        "body-md": ["Noto Sans JP"],
        "label-sm": ["Noto Sans JP"],
        "display-lg": ["Noto Serif JP"],
        "headline-lg": ["Noto Serif JP"],
        "headline-lg-mobile": ["Noto Serif JP"],
        "en": ["Helvetica Neue", "Arial", "sans-serif"]
      },
      "fontSize": {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "36px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "30px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "64px", "letterSpacing": "0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "44px", "letterSpacing": "0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "34px", "fontWeight": "700" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
